# Render docs/wiring/*.svg to PNGs and one PDF.
#
# The SVGs are the source of truth and are generated by tools/wiringgen.py from
# hal/pins.h and docs/BENCH_WIRING.md.  This script only rasterises them, using
# Edge headless because this machine has no Inkscape, no ImageMagick and no
# cairo - and Edge is the same engine that renders every other page in this
# repo, so what you see here is what a browser shows.
#
#   .\tools\wiringgen.py        # first: regenerate the SVGs
#   .\tools\wiringrender.ps1    # then: PNGs + PDF
$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$dir = Join-Path $root "docs\wiring"
$edge = "${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe"
if (-not (Test-Path $edge)) { $edge = "$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe" }
if (-not (Test-Path $edge)) { throw "Edge not found; install it or use another SVG renderer" }

$svgs = Get-ChildItem (Join-Path $dir "p*.svg") | Sort-Object Name
if ($svgs.Count -eq 0) { throw "no SVGs in $dir - run tools/wiringgen.py first" }

# --- PNGs ------------------------------------------------------------------
foreach ($s in $svgs) {
    $png = [IO.Path]::ChangeExtension($s.FullName, ".png")
    $uri = "file:///" + ($s.FullName -replace '\\', '/')
    # Start-Process, not the call operator: PowerShell 5.1 turns a native exe's
    # stderr into a terminating NativeCommandError under -ErrorActionPreference
    # Stop, and Edge writes its progress there even on success.
    $a = @("--headless=new", "--disable-gpu", "--no-sandbox", "--hide-scrollbars",
           "--force-device-scale-factor=1", "--window-size=1600,1131",
           "--screenshot=$png", $uri)
    Start-Process -FilePath $edge -ArgumentList $a -Wait -NoNewWindow | Out-Null
    if (-not (Test-Path $png)) { throw "failed to render $($s.Name)" }
    "  {0,-10} {1,8:N0} bytes" -f $s.BaseName, (Get-Item $png).Length
}

# --- one PDF ---------------------------------------------------------------
$html = Join-Path $dir "_all.html"
$sb = [Text.StringBuilder]::new()
[void]$sb.AppendLine('<!doctype html><meta charset="utf-8"><style>')
[void]$sb.AppendLine('@page { size: 1600px 1131px; margin: 0 }')
[void]$sb.AppendLine('html,body{margin:0;padding:0;background:#fff}')
[void]$sb.AppendLine('img{display:block;width:1600px;height:1131px;page-break-after:always;break-after:page}')
[void]$sb.AppendLine('img:last-child{page-break-after:auto;break-after:auto}')
[void]$sb.AppendLine('</style>')
foreach ($s in $svgs) { [void]$sb.AppendLine("<img src=""$($s.Name)"">") }
Set-Content -Path $html -Value $sb.ToString() -Encoding utf8

$pdf = Join-Path $dir "bench-wiring.pdf"
$uri = "file:///" + ($html -replace '\\', '/')
$a = @("--headless=new", "--disable-gpu", "--no-sandbox", "--no-pdf-header-footer",
       "--print-to-pdf=$pdf", $uri)
Start-Process -FilePath $edge -ArgumentList $a -Wait -NoNewWindow | Out-Null
Remove-Item $html -Force
if (-not (Test-Path $pdf)) { throw "PDF render failed" }
"  {0,-10} {1,8:N0} bytes" -f "PDF", (Get-Item $pdf).Length
