// GENERATED by test/host/gen_traces.cpp - DO NOT EDIT.
// Traces recorded from the REAL ModeManager/FrameScheduler.
window.SWAN_RING = {
 "schema": 2,
 "generated_from": [
  "docs/ref/manifest_cols1234.json",
  "docs/ref/manifest_col5.json"
 ],
 "ring_version": "v3 — descending",
 "frozen": "2026-08-22",
 "direction": "descending",
 "slot_count": 50,
 "slots": [
  {
   "i": 0,
   "id": "blank",
   "label": "blank",
   "cat": "blank"
  },
  {
   "i": 1,
   "id": "wifi",
   "label": "wifi glyph (boot/no-signal state)",
   "cat": "wifi"
  },
  {
   "i": 2,
   "id": "cycle",
   "label": "circle/cycle",
   "cat": "glyph"
  },
  {
   "i": 3,
   "id": "hourglass",
   "label": "hourglass",
   "cat": "glyph"
  },
  {
   "i": 4,
   "id": "boat",
   "label": "boat",
   "cat": "glyph"
  },
  {
   "i": 5,
   "id": "scarab",
   "label": "scarab",
   "cat": "glyph"
  },
  {
   "i": 6,
   "id": "serpent",
   "label": "serpent",
   "cat": "glyph"
  },
  {
   "i": 7,
   "id": "boundloop",
   "label": "bound loop",
   "cat": "glyph"
  },
  {
   "i": 8,
   "id": "jackal",
   "label": "jackal",
   "cat": "glyph"
  },
  {
   "i": 9,
   "id": "lotus",
   "label": "lotus",
   "cat": "glyph"
  },
  {
   "i": 10,
   "id": "armoffer",
   "label": "arm/offering",
   "cat": "glyph"
  },
  {
   "i": 11,
   "id": "ankh",
   "label": "ankh",
   "cat": "glyph"
  },
  {
   "i": 12,
   "id": "djed",
   "label": "djed pillar",
   "cat": "glyph"
  },
  {
   "i": 13,
   "id": "eye",
   "label": "eye of Horus",
   "cat": "glyph"
  },
  {
   "i": 14,
   "id": "duat",
   "label": "duat",
   "cat": "glyph"
  },
  {
   "i": 15,
   "id": "sunrise",
   "label": "sunrise/horizon",
   "cat": "glyph"
  },
  {
   "i": 16,
   "id": "palm",
   "label": "palm/year",
   "cat": "glyph"
  },
  {
   "i": 17,
   "id": "qmark",
   "label": "? (unknown)",
   "cat": "glyph"
  },
  {
   "i": 18,
   "id": "moon",
   "label": "moon/month",
   "cat": "glyph"
  },
  {
   "i": 19,
   "id": "sun",
   "label": "sun/day",
   "cat": "glyph"
  },
  {
   "i": 20,
   "id": "zig",
   "label": "zig",
   "cat": "glyph"
  },
  {
   "i": 21,
   "id": "arch",
   "label": "arch/tunnel",
   "cat": "glyph"
  },
  {
   "i": 22,
   "id": "vloop",
   "label": "vertical loop",
   "cat": "glyph"
  },
  {
   "i": 23,
   "id": "fork",
   "label": "forked branch",
   "cat": "glyph"
  },
  {
   "i": 24,
   "id": "hook",
   "label": "curved hook",
   "cat": "glyph"
  },
  {
   "i": 25,
   "id": "wave",
   "label": "breaking wave",
   "cat": "glyph"
  },
  {
   "i": 26,
   "id": "halfdisc",
   "label": "half-disc",
   "cat": "glyph"
  },
  {
   "i": 27,
   "id": "jellyfish",
   "label": "umbrella/jellyfish",
   "cat": "glyph"
  },
  {
   "i": 28,
   "id": "waves",
   "label": "ocean waves",
   "cat": "glyph"
  },
  {
   "i": 29,
   "id": "stripedisc",
   "label": "striped disc",
   "cat": "glyph"
  },
  {
   "i": 30,
   "id": "hand",
   "label": "hand/arm",
   "cat": "glyph"
  },
  {
   "i": 31,
   "id": "seated",
   "label": "seated figure",
   "cat": "glyph"
  },
  {
   "i": 32,
   "id": "gate",
   "label": "gate",
   "cat": "glyph"
  },
  {
   "i": 33,
   "id": "branch",
   "label": "bent branch",
   "cat": "glyph"
  },
  {
   "i": 34,
   "id": "bird",
   "label": "bird",
   "cat": "glyph"
  },
  {
   "i": 35,
   "id": "obelisk",
   "label": "loop/obelisk",
   "cat": "glyph"
  },
  {
   "i": 36,
   "id": "spiral",
   "label": "spiral coil",
   "cat": "glyph"
  },
  {
   "i": 37,
   "id": "staff",
   "label": "hooked staff",
   "cat": "glyph"
  },
  {
   "i": 38,
   "id": "PM",
   "label": "PM",
   "cat": "ampm"
  },
  {
   "i": 39,
   "id": "AM",
   "label": "AM",
   "cat": "ampm"
  },
  {
   "i": 40,
   "id": "9",
   "label": "digit 9",
   "cat": "digit"
  },
  {
   "i": 41,
   "id": "8",
   "label": "digit 8",
   "cat": "digit"
  },
  {
   "i": 42,
   "id": "7",
   "label": "digit 7",
   "cat": "digit"
  },
  {
   "i": 43,
   "id": "6",
   "label": "digit 6",
   "cat": "digit"
  },
  {
   "i": 44,
   "id": "5",
   "label": "digit 5",
   "cat": "digit"
  },
  {
   "i": 45,
   "id": "4",
   "label": "digit 4",
   "cat": "digit"
  },
  {
   "i": 46,
   "id": "3",
   "label": "digit 3",
   "cat": "digit"
  },
  {
   "i": 47,
   "id": "2",
   "label": "digit 2",
   "cat": "digit"
  },
  {
   "i": 48,
   "id": "1",
   "label": "digit 1",
   "cat": "digit"
  },
  {
   "i": 49,
   "id": "0",
   "label": "digit 0",
   "cat": "digit"
  }
 ],
 "columns": [
  {
   "scheme": "minutes"
  },
  {
   "scheme": "minutes"
  },
  {
   "scheme": "minutes"
  },
  {
   "scheme": "seconds"
  },
  {
   "scheme": "seconds",
   "ring": [
    {
     "i": 0,
     "id": "blank",
     "label": "blank",
     "cat": "blank"
    },
    {
     "i": 1,
     "id": "hourglass",
     "label": "hourglass",
     "cat": "glyph"
    },
    {
     "i": 2,
     "id": "boat",
     "label": "boat",
     "cat": "glyph"
    },
    {
     "i": 3,
     "id": "scarab",
     "label": "scarab",
     "cat": "glyph"
    },
    {
     "i": 4,
     "id": "serpent",
     "label": "serpent",
     "cat": "glyph"
    },
    {
     "i": 5,
     "id": "boundloop",
     "label": "bound loop",
     "cat": "glyph"
    },
    {
     "i": 6,
     "id": "jackal",
     "label": "jackal",
     "cat": "glyph"
    },
    {
     "i": 7,
     "id": "lotus",
     "label": "lotus",
     "cat": "glyph"
    },
    {
     "i": 8,
     "id": "armoffer",
     "label": "arm/offering",
     "cat": "glyph"
    },
    {
     "i": 9,
     "id": "ankh",
     "label": "ankh",
     "cat": "glyph"
    },
    {
     "i": 10,
     "id": "djed",
     "label": "djed pillar",
     "cat": "glyph"
    },
    {
     "i": 11,
     "id": "eye",
     "label": "eye of Horus",
     "cat": "glyph"
    },
    {
     "i": 12,
     "id": "duat",
     "label": "duat",
     "cat": "glyph"
    },
    {
     "i": 13,
     "id": "sunrise",
     "label": "sunrise/horizon",
     "cat": "glyph"
    },
    {
     "i": 14,
     "id": "palm",
     "label": "palm/year",
     "cat": "glyph"
    },
    {
     "i": 15,
     "id": "9",
     "label": "digit 9",
     "cat": "digit"
    },
    {
     "i": 16,
     "id": "8",
     "label": "digit 8",
     "cat": "digit"
    },
    {
     "i": 17,
     "id": "7",
     "label": "digit 7",
     "cat": "digit"
    },
    {
     "i": 18,
     "id": "6",
     "label": "digit 6",
     "cat": "digit"
    },
    {
     "i": 19,
     "id": "5",
     "label": "digit 5",
     "cat": "digit"
    },
    {
     "i": 20,
     "id": "4",
     "label": "digit 4",
     "cat": "digit"
    },
    {
     "i": 21,
     "id": "3",
     "label": "digit 3",
     "cat": "digit"
    },
    {
     "i": 22,
     "id": "2",
     "label": "digit 2",
     "cat": "digit"
    },
    {
     "i": 23,
     "id": "1",
     "label": "digit 1",
     "cat": "digit"
    },
    {
     "i": 24,
     "id": "0",
     "label": "digit 0",
     "cat": "digit"
    },
    {
     "i": 25,
     "id": "qmark",
     "label": "? (unknown)",
     "cat": "glyph"
    },
    {
     "i": 26,
     "id": "moon",
     "label": "moon/month",
     "cat": "glyph"
    },
    {
     "i": 27,
     "id": "sun",
     "label": "sun/day",
     "cat": "glyph"
    },
    {
     "i": 28,
     "id": "wave",
     "label": "breaking wave",
     "cat": "glyph"
    },
    {
     "i": 29,
     "id": "jellyfish",
     "label": "umbrella/jellyfish",
     "cat": "glyph"
    },
    {
     "i": 30,
     "id": "waves",
     "label": "ocean waves",
     "cat": "glyph"
    },
    {
     "i": 31,
     "id": "stripedisc",
     "label": "striped disc",
     "cat": "glyph"
    },
    {
     "i": 32,
     "id": "hand",
     "label": "hand/arm",
     "cat": "glyph"
    },
    {
     "i": 33,
     "id": "seated",
     "label": "seated figure",
     "cat": "glyph"
    },
    {
     "i": 34,
     "id": "gate",
     "label": "gate",
     "cat": "glyph"
    },
    {
     "i": 35,
     "id": "branch",
     "label": "bent branch",
     "cat": "glyph"
    },
    {
     "i": 36,
     "id": "bird",
     "label": "bird",
     "cat": "glyph"
    },
    {
     "i": 37,
     "id": "obelisk",
     "label": "loop/obelisk",
     "cat": "glyph"
    },
    {
     "i": 38,
     "id": "spiral",
     "label": "spiral coil",
     "cat": "glyph"
    },
    {
     "i": 39,
     "id": "staff",
     "label": "hooked staff",
     "cat": "glyph"
    },
    {
     "i": 40,
     "id": "9",
     "label": "digit 9",
     "cat": "digit"
    },
    {
     "i": 41,
     "id": "8",
     "label": "digit 8",
     "cat": "digit"
    },
    {
     "i": 42,
     "id": "7",
     "label": "digit 7",
     "cat": "digit"
    },
    {
     "i": 43,
     "id": "6",
     "label": "digit 6",
     "cat": "digit"
    },
    {
     "i": 44,
     "id": "5",
     "label": "digit 5",
     "cat": "digit"
    },
    {
     "i": 45,
     "id": "4",
     "label": "digit 4",
     "cat": "digit"
    },
    {
     "i": 46,
     "id": "3",
     "label": "digit 3",
     "cat": "digit"
    },
    {
     "i": 47,
     "id": "2",
     "label": "digit 2",
     "cat": "digit"
    },
    {
     "i": 48,
     "id": "1",
     "label": "digit 1",
     "cat": "digit"
    },
    {
     "i": 49,
     "id": "0",
     "label": "digit 0",
     "cat": "digit"
    }
   ]
  }
 ],
 "schemes": {
  "minutes": {
   "card": {
    "default": "#181818"
   },
   "ink": {
    "default": "#e8e4da",
    "glyph": "#b03a2e"
   }
  },
  "seconds": {
   "card": {
    "default": "#e8e4da",
    "glyph": "#b03a2e"
   },
   "ink": {
    "default": "#181818"
   }
  }
 }
}
;

window.SWAN_TRACES = {
  "clock": {
    "desc": "Clock at 15-min granularity: 11:00 then 11:15",
    "events": [
      {"t": 0, "e":"go","col":0,"idx":39,"flaps":15},
      {"t": 0, "e":"go","col":1,"idx":48,"flaps":15},
      {"t": 0, "e":"go","col":2,"idx":49,"flaps":15},
      {"t": 0, "e":"go","col":3,"idx":45,"flaps":15},
      {"t": 0, "e":"go","col":4,"idx":19,"flaps":15},
      {"t": 0, "e":"mode","name":"clock"},
      {"t": 125000, "e":"go","col":2,"idx":48,"flaps":15},
      {"t": 125000, "e":"go","col":3,"idx":49,"flaps":15},
      {"t": 125000, "e":"go","col":4,"idx":24,"flaps":15},
      {"t": 1025000, "e":"go","col":3,"idx":48,"flaps":15},
      {"t": 1025000, "e":"go","col":4,"idx":44,"flaps":15}
    ]
  },
  "quiet": {
    "desc": "Countdown quiet phase: MMM:00, seconds frozen",
    "events": [
      {"t": 0, "e":"go","col":0,"idx":39,"flaps":15},
      {"t": 0, "e":"go","col":1,"idx":48,"flaps":15},
      {"t": 0, "e":"go","col":2,"idx":49,"flaps":15},
      {"t": 0, "e":"go","col":3,"idx":45,"flaps":15},
      {"t": 0, "e":"go","col":4,"idx":19,"flaps":15},
      {"t": 0, "e":"mode","name":"clock"},
      {"t": 0, "e":"go","col":0,"idx":48,"flaps":15},
      {"t": 0, "e":"go","col":1,"idx":49,"flaps":15},
      {"t": 0, "e":"go","col":2,"idx":41,"flaps":15},
      {"t": 0, "e":"go","col":3,"idx":49,"flaps":15},
      {"t": 0, "e":"go","col":4,"idx":24,"flaps":15},
      {"t": 0, "e":"go","col":2,"idx":42,"flaps":15},
      {"t": 0, "e":"mode","name":"countdown"},
      {"t": 60000, "e":"go","col":2,"idx":43,"flaps":15},
      {"t": 120000, "e":"go","col":2,"idx":44,"flaps":15},
      {"t": 180000, "e":"go","col":2,"idx":45,"flaps":15}
    ]
  },
  "countdown": {
    "desc": "Seconds wake at 004:00, then MMM:SS live",
    "events": [
      {"t": 0, "e":"go","col":0,"idx":39,"flaps":15},
      {"t": 0, "e":"go","col":1,"idx":48,"flaps":15},
      {"t": 0, "e":"go","col":2,"idx":49,"flaps":15},
      {"t": 0, "e":"go","col":3,"idx":45,"flaps":15},
      {"t": 0, "e":"go","col":4,"idx":19,"flaps":15},
      {"t": 0, "e":"mode","name":"clock"},
      {"t": 0, "e":"go","col":0,"idx":49,"flaps":15},
      {"t": 0, "e":"go","col":1,"idx":49,"flaps":15},
      {"t": 0, "e":"go","col":2,"idx":44,"flaps":15},
      {"t": 0, "e":"go","col":3,"idx":49,"flaps":15},
      {"t": 0, "e":"go","col":4,"idx":24,"flaps":15},
      {"t": 0, "e":"mode","name":"countdown"},
      {"t": 2000, "e":"go","col":2,"idx":45,"flaps":15},
      {"t": 59000, "e":"go","col":2,"idx":46,"flaps":15},
      {"t": 59000, "e":"go","col":3,"idx":44,"flaps":15},
      {"t": 59000, "e":"go","col":4,"idx":40,"flaps":15},
      {"t": 62000, "e":"cue","name":"warn_4min"},
      {"t": 63000, "e":"go","col":4,"idx":41,"flaps":15},
      {"t": 64000, "e":"go","col":4,"idx":42,"flaps":15},
      {"t": 65000, "e":"go","col":4,"idx":43,"flaps":15},
      {"t": 66000, "e":"go","col":4,"idx":44,"flaps":15},
      {"t": 67000, "e":"go","col":4,"idx":45,"flaps":15},
      {"t": 68000, "e":"go","col":4,"idx":46,"flaps":15},
      {"t": 69000, "e":"go","col":4,"idx":47,"flaps":15},
      {"t": 70000, "e":"go","col":4,"idx":48,"flaps":15},
      {"t": 71000, "e":"go","col":4,"idx":49,"flaps":15},
      {"t": 71100, "e":"go","col":3,"idx":45,"flaps":15},
      {"t": 71100, "e":"go","col":4,"idx":15,"flaps":15},
      {"t": 73000, "e":"go","col":4,"idx":16,"flaps":15},
      {"t": 74000, "e":"go","col":4,"idx":17,"flaps":15},
      {"t": 75000, "e":"go","col":4,"idx":18,"flaps":15}
    ]
  },
  "tens": {
    "desc": "Same boundary in MMM:S0 - column 5 stays parked",
    "events": [
      {"t": 0, "e":"go","col":0,"idx":39,"flaps":15},
      {"t": 0, "e":"go","col":1,"idx":48,"flaps":15},
      {"t": 0, "e":"go","col":2,"idx":49,"flaps":15},
      {"t": 0, "e":"go","col":3,"idx":45,"flaps":15},
      {"t": 0, "e":"go","col":4,"idx":19,"flaps":15},
      {"t": 0, "e":"mode","name":"clock"},
      {"t": 0, "e":"go","col":0,"idx":49,"flaps":15},
      {"t": 0, "e":"go","col":1,"idx":49,"flaps":15},
      {"t": 0, "e":"go","col":2,"idx":44,"flaps":15},
      {"t": 0, "e":"go","col":3,"idx":49,"flaps":15},
      {"t": 0, "e":"go","col":4,"idx":24,"flaps":15},
      {"t": 0, "e":"mode","name":"countdown"},
      {"t": 2000, "e":"go","col":2,"idx":45,"flaps":15},
      {"t": 59000, "e":"go","col":2,"idx":46,"flaps":15},
      {"t": 59000, "e":"go","col":3,"idx":44,"flaps":15},
      {"t": 62000, "e":"cue","name":"warn_4min"},
      {"t": 72000, "e":"go","col":3,"idx":45,"flaps":15},
      {"t": 82000, "e":"go","col":3,"idx":46,"flaps":15},
      {"t": 92000, "e":"go","col":3,"idx":47,"flaps":15}
    ]
  },
  "zero": {
    "desc": "Last 15 s, zero, alarm spin, hieroglyph reveal",
    "events": [
      {"t": 0, "e":"go","col":0,"idx":39,"flaps":15},
      {"t": 0, "e":"go","col":1,"idx":48,"flaps":15},
      {"t": 0, "e":"go","col":2,"idx":49,"flaps":15},
      {"t": 0, "e":"go","col":3,"idx":45,"flaps":15},
      {"t": 0, "e":"go","col":4,"idx":19,"flaps":15},
      {"t": 0, "e":"mode","name":"clock"},
      {"t": 0, "e":"go","col":0,"idx":49,"flaps":15},
      {"t": 0, "e":"go","col":1,"idx":49,"flaps":15},
      {"t": 0, "e":"go","col":3,"idx":48,"flaps":15},
      {"t": 0, "e":"go","col":4,"idx":20,"flaps":15},
      {"t": 0, "e":"mode","name":"countdown"},
      {"t": 1000, "e":"go","col":4,"idx":21,"flaps":15},
      {"t": 2000, "e":"go","col":4,"idx":22,"flaps":15},
      {"t": 3000, "e":"go","col":4,"idx":23,"flaps":15},
      {"t": 4000, "e":"go","col":4,"idx":24,"flaps":15},
      {"t": 4100, "e":"go","col":3,"idx":49,"flaps":15},
      {"t": 4100, "e":"go","col":4,"idx":40,"flaps":15},
      {"t": 6000, "e":"go","col":4,"idx":41,"flaps":15},
      {"t": 7000, "e":"go","col":4,"idx":42,"flaps":15},
      {"t": 8000, "e":"go","col":4,"idx":43,"flaps":15},
      {"t": 9000, "e":"go","col":4,"idx":44,"flaps":15},
      {"t": 10000, "e":"go","col":4,"idx":45,"flaps":15},
      {"t": 11000, "e":"go","col":4,"idx":46,"flaps":15},
      {"t": 12000, "e":"go","col":4,"idx":47,"flaps":15},
      {"t": 13000, "e":"go","col":4,"idx":48,"flaps":15},
      {"t": 14000, "e":"go","col":4,"idx":49,"flaps":15},
      {"t": 15000, "e":"cue","name":"system_failure"},
      {"t": 18000, "e":"spin","col":0,"flaps":25,"secs":6},
      {"t": 18000, "e":"spin","col":1,"flaps":25,"secs":6},
      {"t": 18000, "e":"spin","col":2,"flaps":25,"secs":6},
      {"t": 18000, "e":"spin","col":3,"flaps":25,"secs":6},
      {"t": 18000, "e":"spin","col":4,"flaps":25,"secs":6},
      {"t": 18100, "e":"go","col":0,"idx":49,"flaps":15},
      {"t": 18100, "e":"go","col":1,"idx":49,"flaps":15},
      {"t": 18100, "e":"go","col":2,"idx":49,"flaps":15},
      {"t": 18100, "e":"go","col":3,"idx":49,"flaps":15},
      {"t": 18100, "e":"go","col":4,"idx":49,"flaps":15},
      {"t": 24000, "e":"go","col":0,"idx":13,"flaps":15},
      {"t": 24000, "e":"go","col":1,"idx":11,"flaps":15},
      {"t": 24000, "e":"go","col":2,"idx":17,"flaps":15},
      {"t": 24000, "e":"go","col":3,"idx":5,"flaps":15},
      {"t": 24000, "e":"go","col":4,"idx":14,"flaps":15}
    ]
  },
  "message": {
    "desc": "Glyph message, dwell back to clock, ????? preset",
    "events": [
      {"t": 0, "e":"go","col":0,"idx":39,"flaps":15},
      {"t": 0, "e":"go","col":1,"idx":48,"flaps":15},
      {"t": 0, "e":"go","col":2,"idx":49,"flaps":15},
      {"t": 0, "e":"go","col":3,"idx":45,"flaps":15},
      {"t": 0, "e":"go","col":4,"idx":19,"flaps":15},
      {"t": 0, "e":"mode","name":"clock"},
      {"t": 0, "e":"go","col":0,"idx":13,"flaps":15},
      {"t": 0, "e":"go","col":1,"idx":0,"flaps":15},
      {"t": 0, "e":"go","col":2,"idx":11,"flaps":15},
      {"t": 0, "e":"go","col":3,"idx":0,"flaps":15},
      {"t": 0, "e":"go","col":4,"idx":3,"flaps":15},
      {"t": 0, "e":"mode","name":"message"},
      {"t": 8000, "e":"go","col":0,"idx":39,"flaps":15},
      {"t": 8000, "e":"go","col":1,"idx":48,"flaps":15},
      {"t": 8000, "e":"go","col":2,"idx":49,"flaps":15},
      {"t": 8000, "e":"go","col":3,"idx":45,"flaps":15},
      {"t": 8000, "e":"go","col":4,"idx":19,"flaps":15},
      {"t": 8000, "e":"mode","name":"clock"},
      {"t": 10000, "e":"go","col":0,"idx":17,"flaps":15},
      {"t": 10000, "e":"go","col":1,"idx":17,"flaps":15},
      {"t": 10000, "e":"go","col":2,"idx":17,"flaps":15},
      {"t": 10000, "e":"go","col":3,"idx":17,"flaps":15},
      {"t": 10000, "e":"go","col":4,"idx":25,"flaps":15},
      {"t": 10000, "e":"mode","name":"message"}
    ]
  },
  "wifi": {
    "desc": "No-signal boot: blank, WiFi glyph at 15 s, then sync",
    "events": [
      {"t": 0, "e":"mode","name":"clock"},
      {"t": 15000, "e":"go","col":2,"idx":1,"flaps":15},
      {"t": 20100, "e":"go","col":0,"idx":39,"flaps":15},
      {"t": 20100, "e":"go","col":1,"idx":48,"flaps":15},
      {"t": 20100, "e":"go","col":2,"idx":49,"flaps":15},
      {"t": 20100, "e":"go","col":3,"idx":45,"flaps":15},
      {"t": 20100, "e":"go","col":4,"idx":19,"flaps":15}
    ]
  }
};
